# -*- mode: ruby -*-

file = File.expand_path('../../../vagrant_helper', __FILE__);
require_relative file

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-vagrant.box"

  config.vm.provider "virtualbox" do |vm|
    vm.name = "Installers Ubuntu 14.04"

    helper = VagrantHelper.new(RbConfig::CONFIG["host_os"])
    vm.memory = helper.memory_fraction(8)
  end
end
