file = File.expand_path('../../../vagrant_helper', __FILE__);
require_relative file

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  # config.vm.box = "bento/ubuntu-18.04"

  config.vm.network "forwarded_port", guest: 80, host: 1404
  config.ssh.forward_agent = true

  config.vm.provider "virtualbox" do |vm|
    vm.name = "Installers Ubuntu 14.04"

    helper = VagrantHelper.new(RbConfig::CONFIG["host_os"])
    vm.memory = helper.memory_fraction(4)
  end
end
