# -*- mode: ruby -*-
# vi: set ft=ruby :

file = File.expand_path('../../../vagrant_helper', __FILE__);
require_relative file

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.ssh.forward_agent = true
end

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Ubuntu 20.04-dev"
    vb.gui = true

    vb.memory = VagrantHelper.new(RbConfig::CONFIG["host_os"]).memory_fraction(2)

    vb.customize ["modifyvm", :id, "--vram", "128"]
    vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxvga"]

    # vb.customize ["modifyvm", :id, "--video", "16MB"] # error

    # vb.customize ["modifyvm", :id, "--monitorcount", "2"]

    # Add an empty optical drive
    vb.customize ['storagectl', :id, '--name', 'IDE Controller', '--add', 'ide']
    vb.customize ['storageattach', :id, '--storagectl', 'IDE Controller', '--port', 0, '--device', 0, '--type', 'dvddrive', '--medium', 'emptydrive']
  end

  config.vm.provision "shell", inline: <<-SHELL
    ./install.sh
  SHELL
end
